import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut, SignIn, UserButton } from "@clerk/nextjs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "News.ly",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <SignedOut>
          <div className="flex items-center justify-center min-h-screen bg-gray-100">
            <SignIn routing="hash" />
          </div>
        </SignedOut>
        <SignedIn>
              {children}
        </SignedIn>
      </body>
    </html>
  </ClerkProvider>
  );
}

